<a href="https://colab.research.google.com/github/17761A04F1/dvproj.github.io/blob/main/ML_first_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("/content/data.csv")

In [3]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [5]:
df.isnull()

id  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    False      False        False         False           False      False   
1    False      False        False         False           False      False   
2    False      False        False         False           False      False   
3    False      False        False         False           False      False   
4    False      False        False         False           False      False   
..     ...        ...          ...           ...             ...        ...   
564  False      False        False         False           False      False   
565  False      False        False         False           False      False   
566  False      False        False         False           False      False   
567  False      False        False         False           False      False   
568  False      False        False         False           False      False   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0              False             False           False                False   
1              False             False           False                False   
2              False             False           False                False   
3              False             False           False                False   
4              False             False           False                False   
..               ...               ...             ...                  ...   
564            False             False           False                False   
565            False             False           False                False   
566            False             False           False                False   
567            False             False           False                False   
568            False             False           False                False   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          False            False       False             False   
1    ...          False            False       False             False   
2    ...          False            False       False             False   
3    ...          False            False       False             False   
4    ...          False            False       False             False   
..   ...            ...              ...         ...               ...   
564  ...          False            False       False             False   
565  ...          False            False       False             False   
566  ...          False            False       False             False   
567  ...          False            False       False             False   
568  ...          False            False       False             False   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0                False            False                 False           False   
1                False            False                 False           False   
2                False            False                 False           False   
3                False            False                 False           False   
4                False            False                 False           False   
..                 ...              ...                   ...             ...   
564              False            False                 False           False   
565              False            False                 False           False   
566              False            False                 False           False   
567              False            False                 False           False   
568              False            False                 False           False   

     fractal_dimension_worst  Unnamed: 32  
0                      False         True  
1                      False         True  
2                      False         True  
3                      False         True  
4                      False

In [6]:
df.isnull().sum().sum()

569

In [7]:
#Dealing with null values

In [8]:
df.drop('Unnamed: 32',inplace=True,axis=1)

In [9]:
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216       

In [10]:
#converting categorical to numerical

In [11]:
df['diagnosis'].replace(['M', 'B'],
                        [0, 1], inplace=True)

In [12]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [13]:
from sklearn.model_selection import train_test_split
y=df['diagnosis']
X=df.drop('diagnosis',axis=1)

In [14]:
X

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302        17.99         10.38          122.80     1001.0   
1      842517        20.57         17.77          132.90     1326.0   
2    84300903        19.69         21.25          130.00     1203.0   
3    84348301        11.42         20.38           77.58      386.1   
4    84358402        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564    926424        21.56         22.39          142.00     1479.0   
565    926682        20.13         28.25          131.20     1261.0   
566    926954        16.60         28.08          108.30      858.1   
567    927241        20.60         29.33          140.10     1265.0   
568     92751         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...

In [15]:

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.2, random_state=100)

In [16]:
y_train

58     1
554    1
351    0
136    1
497    1
      ..
526    1
53     0
350    1
79     1
520    1
Name: diagnosis, Length: 455, dtype: int64

In [17]:
X_test

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
400   90439701       17.910         21.02          124.40      994.0   
225   88143502       14.340         13.47           92.51      641.2   
321     894618       20.160         19.66          131.10     1274.0   
173     871641       11.080         14.71           70.21      372.7   
506   91544001       12.220         20.04           79.47      453.1   
..         ...          ...           ...             ...        ...   
359  901034301        9.436         18.32           59.82      278.6   
261     888264       17.350         23.06          111.00      933.1   
37      854941       13.030         18.42           82.61      523.8   
6       844359       18.250         19.98          119.60     1040.0   
524     917897        9.847         15.68           63.00      293.2   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
400          0.12300           0.25760         0.31890              0.11980   
225          0.09906           0.07624         0.05724              0.04603   
321          0.08020           0.08564         0.11550              0.07726   
173          0.10060           0.05743         0.02363              0.02583   
506          0.10960           0.11520         0.08175              0.02166   
..               ...               ...             ...                  ...   
359          0.10090           0.05956         0.02710              0.01406   
261          0.08662           0.06290         0.02891              0.02837   
37           0.08983           0.03766         0.02562              0.02923   
6            0.09463           0.10900         0.11270              0.07400   
524          0.09492           0.08419         0.02330              0.02416   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
400         0.2113  ...         20.80          27.78           149.60   
225         0.2075  ...         16.77          16.90           110.40   
321         0.1928  ...         23.06          23.03           150.20   
173         0.1566  ...         11.35          16.82            72.01   
506         0.2124  ...         13.16          24.17            85.13   
..             ...  ...           ...            ...              ...   
359         0.1506  ...         12.02          25.02            75.79   
261         0.1564  ...         19.85          31.47           128.20   
37          0.1467  ...         13.30          22.81            84.46   
6           0.1794  ...         22.88          27.66           153.20   
524         0.1387  ...         11.24          22.99            74.32   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
400      1304.0           0.18730            0.59170          0.90340   
225       873.2           0.12970            0.15250          0.16320   
321      1657.0           0.10540            0.15370          0.26060   
173       396.5           0.12160            0.08240          0.03938   
506       515.3           0.14020            0.23150          0.35350   
..          ...               ...                ...              ...   
359       439.6           0.13330            0.10490          0.11440   
261      1218.0           0.12400            0.14860          0.12110   
37        545.9           0.09701            0.04619          0.04833   
6        1606.0           0.14420            0.25760          0.37840   
524       376.5           0.14190            0.22430          0.08434   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
400               0.19640          0.3245                  0.11980  
225               0.10870          0.3062                  0.06072  
321               0.14250          0.3055                  0.05933  
173               0.04306          0.1902                  0.07313  
506               0.08088          0.2709                  0.08839  
..                    ...     

In [18]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [19]:
y_train_pred=lr.predict(X_train)
y_test_pred=lr.predict(X_test)


In [20]:
# evaluating model performance

In [21]:
c=0
for i in y_train:
  if i==1:
    c=c+1
print(c)

292


In [22]:
from sklearn.metrics import mean_squared_error,r2_score,accuracy_score
lr_train_accuracy=accuracy_score(y_train,y_train_pred)
lr_train_r2=r2_score(y_train,y_train_pred)
lr_train_mse=mean_squared_error(y_train,y_train_pred)
lr_test_r2=r2_score(y_test,y_test_pred)
lr_test_mse=mean_squared_error(y_test,y_test_pred)

In [23]:
lr_train_r2

-0.5582191780821921

In [24]:
lr_train_mse

0.35824175824175825

In [25]:
lr_test_r2

-0.7538461538461536

In [26]:
lr_test_mse

0.4298245614035088

In [27]:
LR_results=pd.DataFrame(['Linear Regression',lr_train_mse,lr_train_r2,lr_test_mse,lr_test_r2]).transpose()
LR_results.columns=['Method','Training MSE','Training R2','Test MSE','Test R2']

In [28]:
LR_results

Method Training MSE Training R2  Test MSE   Test R2
0  Linear Regression     0.358242   -0.558219  0.429825 -0.753846

In [29]:
#Random forest

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [31]:
rf=RandomForestClassifier(max_depth=2,random_state=100)
rf.fit(X_train,y_train)


RandomForestClassifier(max_depth=2, random_state=100)

In [32]:
y_trainrf_pred=rf.predict(X_train)
y_testrf_pred=rf.predict(X_test)


In [33]:
from sklearn.metrics import mean_squared_error,r2_score
rf_train_r2=r2_score(y_train,y_trainrf_pred)
rf_train_mse=mean_squared_error(y_train,y_trainrf_pred)
rf_test_r2=r2_score(y_test,y_testrf_pred)
rf_test_mse=mean_squared_error(y_test,y_testrf_pred)

In [34]:
RF_results=pd.DataFrame(['Random Forest',rf_train_mse,rf_train_r2,rf_test_mse,rf_test_r2]).transpose()
RF_results.columns=['Method','Training MSE','Training R2','Test MSE','Test R2']

In [35]:
RF_results

Method Training MSE Training R2  Test MSE   Test R2
0  Random Forest     0.043956    0.808807  0.052632  0.785243

In [36]:
df_models=pd.concat([LR_results,RF_results],axis=0)

In [37]:
df_models

Method Training MSE Training R2  Test MSE   Test R2
0  Linear Regression     0.358242   -0.558219  0.429825 -0.753846
0      Random Forest     0.043956    0.808807  0.052632  0.785243

In [38]:

# import the regressor
from sklearn.tree import DecisionTreeClassifier

# create a regressor object
dt = DecisionTreeClassifier(random_state = 0)

In [39]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(random_state=0)

In [40]:
y_traindt_pred=dt.predict(X_train)
y_testdt_pred=dt.predict(X_test)

In [41]:
from sklearn.metrics import mean_squared_error,r2_score,accuracy_score
dt_train_r2=r2_score(y_train,y_traindt_pred)
dt_train_mse=mean_squared_error(y_train,y_traindt_pred)
dt_test_r2=r2_score(y_test,y_testdt_pred)
dt_test_mse=mean_squared_error(y_test,y_testdt_pred)

In [42]:
DT_results=pd.DataFrame(['Decision Tree',dt_train_mse,dt_train_r2,dt_test_mse,dt_test_r2]).transpose()
DT_results.columns=['Method','Training MSE','Training R2','Test MSE','Test R2']

In [43]:
DT_results

Method Training MSE Training R2 Test MSE   Test R2
0  Decision Tree          0.0         1.0  0.04386  0.821036

In [44]:
df_models=pd.concat([LR_results,RF_results,DT_results],axis=0)

In [45]:
df_models

Method Training MSE Training R2  Test MSE   Test R2
0  Linear Regression     0.358242   -0.558219  0.429825 -0.753846
0      Random Forest     0.043956    0.808807  0.052632  0.785243
0      Decision Tree          0.0         1.0   0.04386  0.821036

In [46]:
from sklearn import svm

In [47]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler

In [48]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [49]:
ksvm = svm.SVC(kernel='rbf',
               gamma=0.1,
               C=10.0)

# Train the model on the training data
ksvm.fit(X_train, y_train)
y_trainksvm_pred=ksvm.predict(X_train)
y_testksvm_pred=ksvm.predict(X_test)
ksvm_train_r2=r2_score(y_train,y_trainksvm_pred)
ksvm_train_mse=mean_squared_error(y_train,y_trainksvm_pred)
ksvm_test_r2=r2_score(y_test,y_testksvm_pred)
ksvm_test_mse=mean_squared_error(y_test,y_testksvm_pred)

# Evaluate the model on the test data
accuracy = accuracy_score(y_test, y_testksvm_pred)
print('Accuracy:', accuracy)

Accuracy: 0.9736842105263158


In [50]:
SVM_results=pd.DataFrame(['Decision Tree',ksvm_train_mse,ksvm_train_r2,ksvm_test_mse,ksvm_test_r2]).transpose()
SVM_results.columns=['Method','Training MSE','Training R2','Test MSE','Test R2']

In [51]:
y_test

400    0
225    1
321    0
173    1
506    1
      ..
359    1
261    0
37     1
6      0
524    1
Name: diagnosis, Length: 114, dtype: int64

In [52]:
y_testksvm_pred

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1])

In [53]:
SVM_results

Method Training MSE Training R2  Test MSE   Test R2
0  Decision Tree          0.0         1.0  0.026316  0.892622

In [54]:
confusion_matrix(y_test, y_testksvm_pred)


array([[47,  2],
       [ 1, 64]])

In [55]:
confusion_matrix(y_test,y_testdt_pred)

array([[46,  3],
       [ 2, 63]])

In [56]:
accuracy = accuracy_score(y_test, y_testdt_pred)
accuracy

0.956140350877193

In [57]:
df_models=pd.concat([LR_results,RF_results,DT_results,SVM_results],axis=0)
df_models

Method Training MSE Training R2  Test MSE   Test R2
0  Linear Regression     0.358242   -0.558219  0.429825 -0.753846
0      Random Forest     0.043956    0.808807  0.052632  0.785243
0      Decision Tree          0.0         1.0   0.04386  0.821036
0      Decision Tree          0.0         1.0  0.026316  0.892622

In [58]:
ksvm.predict(np.array(pd.DataFrame(X_test).iloc[2]).reshape(1,-1))

array([0])

In [59]:
df.iloc[2]

id                         8.430090e+07
diagnosis                  0.000000e+00
radius_mean                1.969000e+01
texture_mean               2.125000e+01
perimeter_mean             1.300000e+02
area_mean                  1.203000e+03
smoothness_mean            1.096000e-01
compactness_mean           1.599000e-01
concavity_mean             1.974000e-01
concave points_mean        1.279000e-01
symmetry_mean              2.069000e-01
fractal_dimension_mean     5.999000e-02
radius_se                  7.456000e-01
texture_se                 7.869000e-01
perimeter_se               4.585000e+00
area_se                    9.403000e+01
smoothness_se              6.150000e-03
compactness_se             4.006000e-02
concavity_se               3.832000e-02
concave points_se          2.058000e-02
symmetry_se                2.250000e-02
fractal_dimension_se       4.571000e-03
radius_worst               2.357000e+01
texture_worst              2.553000e+01
perimeter_worst            1.525000e+02


In [60]:
y_test

400    0
225    1
321    0
173    1
506    1
      ..
359    1
261    0
37     1
6      0
524    1
Name: diagnosis, Length: 114, dtype: int64

In [62]:
import pickle

In [68]:
pickle.dump(ksvm, open('/content/ksvm_model', 'wb'))

In [73]:
pickled_model = pickle.load(open('/content/ksvm_model', 'rb'))
pickled_model.predict(X_test)

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1])

In [77]:
y_testksvm_pred

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1])