<a href="https://colab.research.google.com/github/17761A04F1/dvproj.github.io/blob/main/ML_first_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#imported necessary libraries
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("/content/data.csv") #read the csv file

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [4]:
df.isnull()

id  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    False      False        False         False           False      False   
1    False      False        False         False           False      False   
2    False      False        False         False           False      False   
3    False      False        False         False           False      False   
4    False      False        False         False           False      False   
..     ...        ...          ...           ...             ...        ...   
564  False      False        False         False           False      False   
565  False      False        False         False           False      False   
566  False      False        False         False           False      False   
567  False      False        False         False           False      False   
568  False      False        False         False           False      False   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0              False             False           False                False   
1              False             False           False                False   
2              False             False           False                False   
3              False             False           False                False   
4              False             False           False                False   
..               ...               ...             ...                  ...   
564            False             False           False                False   
565            False             False           False                False   
566            False             False           False                False   
567            False             False           False                False   
568            False             False           False                False   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          False            False       False             False   
1    ...          False            False       False             False   
2    ...          False            False       False             False   
3    ...          False            False       False             False   
4    ...          False            False       False             False   
..   ...            ...              ...         ...               ...   
564  ...          False            False       False             False   
565  ...          False            False       False             False   
566  ...          False            False       False             False   
567  ...          False            False       False             False   
568  ...          False            False       False             False   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0                False            False                 False           False   
1                False            False                 False           False   
2                False            False                 False           False   
3                False            False                 False           False   
4                False            False                 False           False   
..                 ...              ...                   ...             ...   
564              False            False                 False           False   
565              False            False                 False           False   
566              False            False                 False           False   
567              False            False                 False           False   
568              False            False                 False           False   

     fractal_dimension_worst  Unnamed: 32  
0                      False         True  
1                      False         True  
2                      False         True  
3                      False         True  
4                      False

In [5]:
#Dealing with null values

In [6]:
df.drop('Unnamed: 32',inplace=True,axis=1)

In [7]:
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216       

In [8]:
#converting categorical to numerical

In [9]:
df['diagnosis'].replace(['M', 'B'],
                        [0, 1], inplace=True)

In [10]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [11]:
#given values to variables X and y for converting into training and testing data
from sklearn.model_selection import train_test_split
y=df['diagnosis']
X=df.drop('diagnosis',axis=1)

In [12]:
X

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302        17.99         10.38          122.80     1001.0   
1      842517        20.57         17.77          132.90     1326.0   
2    84300903        19.69         21.25          130.00     1203.0   
3    84348301        11.42         20.38           77.58      386.1   
4    84358402        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564    926424        21.56         22.39          142.00     1479.0   
565    926682        20.13         28.25          131.20     1261.0   
566    926954        16.60         28.08          108.30      858.1   
567    927241        20.60         29.33          140.10     1265.0   
568     92751         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...

In [13]:
#splitted the data, here 80% of the data is under training and 20% is testing
#random state controls the shuffling process
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.2, random_state=100)

In [14]:
#I have taken logistic regression ML
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [15]:
y_train_pred=lr.predict(X_train)
y_test_pred=lr.predict(X_test)


In [16]:
# evaluating model performance

In [17]:
from sklearn.metrics import mean_squared_error,r2_score,accuracy_score
lr_train_accuracy=accuracy_score(y_train,y_train_pred)
lr_train_r2=r2_score(y_train,y_train_pred)
lr_train_mse=mean_squared_error(y_train,y_train_pred)
lr_test_r2=r2_score(y_test,y_test_pred)
lr_test_mse=mean_squared_error(y_test,y_test_pred)

In [18]:
LR_results=pd.DataFrame(['Linear Regression',lr_train_mse,lr_train_r2,lr_test_mse,lr_test_r2]).transpose()
LR_results.columns=['Method','Training MSE','Training R2','Test MSE','Test R2']

In [19]:
LR_results

Method Training MSE Training R2  Test MSE   Test R2
0  Linear Regression     0.358242   -0.558219  0.429825 -0.753846

In [20]:
#Random forest

In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
rf=RandomForestClassifier(max_depth=2,random_state=100)
rf.fit(X_train,y_train)


RandomForestClassifier(max_depth=2, random_state=100)

In [23]:
y_trainrf_pred=rf.predict(X_train)
y_testrf_pred=rf.predict(X_test)


In [24]:
from sklearn.metrics import mean_squared_error,r2_score
rf_train_r2=r2_score(y_train,y_trainrf_pred)
rf_train_mse=mean_squared_error(y_train,y_trainrf_pred)
rf_test_r2=r2_score(y_test,y_testrf_pred)
rf_test_mse=mean_squared_error(y_test,y_testrf_pred)

In [25]:
RF_results=pd.DataFrame(['Random Forest',rf_train_mse,rf_train_r2,rf_test_mse,rf_test_r2]).transpose()
RF_results.columns=['Method','Training MSE','Training R2','Test MSE','Test R2']

In [26]:
RF_results

Method Training MSE Training R2  Test MSE   Test R2
0  Random Forest     0.043956    0.808807  0.052632  0.785243

In [27]:

# import the regressor
from sklearn.tree import DecisionTreeClassifier

# create a regressor object
dt = DecisionTreeClassifier(random_state = 0)

In [28]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(random_state=0)

In [29]:
y_traindt_pred=dt.predict(X_train)
y_testdt_pred=dt.predict(X_test)

In [30]:
from sklearn.metrics import mean_squared_error,r2_score,accuracy_score
dt_train_r2=r2_score(y_train,y_traindt_pred)
dt_train_mse=mean_squared_error(y_train,y_traindt_pred)
dt_test_r2=r2_score(y_test,y_testdt_pred)
dt_test_mse=mean_squared_error(y_test,y_testdt_pred)

In [31]:
DT_results=pd.DataFrame(['Decision Tree',dt_train_mse,dt_train_r2,dt_test_mse,dt_test_r2]).transpose()
DT_results.columns=['Method','Training MSE','Training R2','Test MSE','Test R2']

In [32]:
DT_results

Method Training MSE Training R2 Test MSE   Test R2
0  Decision Tree          0.0         1.0  0.04386  0.821036

In [33]:
from sklearn import svm

In [34]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler

In [35]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [36]:
ksvm = svm.SVC(kernel='rbf',
               gamma=0.1,
               C=10.0)

# Train the model on the training data
ksvm.fit(X_train, y_train)
y_trainksvm_pred=ksvm.predict(X_train)
y_testksvm_pred=ksvm.predict(X_test)
ksvm_train_r2=r2_score(y_train,y_trainksvm_pred)
ksvm_train_mse=mean_squared_error(y_train,y_trainksvm_pred)
ksvm_test_r2=r2_score(y_test,y_testksvm_pred)
ksvm_test_mse=mean_squared_error(y_test,y_testksvm_pred)

# Evaluate the model on the test data
accuracy = accuracy_score(y_test, y_testksvm_pred)
print('Accuracy:', accuracy)

Accuracy: 0.9736842105263158


In [37]:
SVM_results=pd.DataFrame(['SVM',ksvm_train_mse,ksvm_train_r2,ksvm_test_mse,ksvm_test_r2]).transpose()
SVM_results.columns=['Method','Training MSE','Training R2','Test MSE','Test R2']

In [38]:
y_test

400    0
225    1
321    0
173    1
506    1
      ..
359    1
261    0
37     1
6      0
524    1
Name: diagnosis, Length: 114, dtype: int64

In [39]:
y_testksvm_pred

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1])

In [40]:
SVM_results

Method Training MSE Training R2  Test MSE   Test R2
0    SVM          0.0         1.0  0.026316  0.892622

In [41]:
confusion_matrix(y_test, y_testksvm_pred)


array([[47,  2],
       [ 1, 64]])

In [42]:
confusion_matrix(y_test,y_testdt_pred)

array([[46,  3],
       [ 2, 63]])

In [43]:
accuracy = accuracy_score(y_test, y_testdt_pred)
accuracy

0.956140350877193

In [44]:
df_models=pd.concat([LR_results,RF_results,DT_results,SVM_results],axis=0)
df_models

Method Training MSE Training R2  Test MSE   Test R2
0  Linear Regression     0.358242   -0.558219  0.429825 -0.753846
0      Random Forest     0.043956    0.808807  0.052632  0.785243
0      Decision Tree          0.0         1.0   0.04386  0.821036
0                SVM          0.0         1.0  0.026316  0.892622

In [47]:
#Predicted the X_test[2] using ksvm because by looking on above metrics KSVM is best compared to remaing ML models
ksvm.predict(np.array(pd.DataFrame(X_test).iloc[2]).reshape(1,-1))

array([0])

In [48]:
y_test

400    0
225    1
321    0
173    1
506    1
      ..
359    1
261    0
37     1
6      0
524    1
Name: diagnosis, Length: 114, dtype: int64

In [53]:
#pickling is done beacuse this helps in predicting values in other machines, we need not run entire code
import pickle

In [54]:
pickle.dump(ksvm, open('/content/ksvm_model', 'wb'))

In [55]:
pickled_model = pickle.load(open('/content/ksvm_model', 'rb'))
pickled_model.predict(X_test)

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1])

In [56]:
y_testksvm_pred

array([0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1])